version: '3.1'

services:

  local_db:
    image: mysql:5.7.27
    container_name: local_db
    restart: always
    env_file: .env
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      TZ: Etc/Greenwich
    ports:
      - "3300:3306"
    expose:
      - "3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: